# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: config-server-app
# spec:
#   replicas: 2 
#   selector:
#     matchLabels:
#       app: config-server-app
#   template:
#     metadata:
#       labels:
#         app: config-server-app
#     spec:
#       containers:
#       - name: config-server-app
#         image: algabrizaid/configserver:latest-16
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 9296
#         env:
#           - name: EUREKA_SERVER_ADDRESS
#             valueFrom:
#               configMapKeyRef:
#                 name: eureka-cm
#                 key: eureka_service_address
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      initContainers:
      - name: init-config-server
        image: busybox
        command: ['sh', '-c', 'until curl http://eureka-0.eureka:8761/eureka; do echo waiting for eureka; sleep 2; done']
      containers:
      - name: config-server-app
        image: algabrizaid/configserver:latest-16
        imagePullPolicy: Always
        ports:
        - containerPort: 9296
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address

---

apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  selector:
    app: config-server-app
  ports:
  - port: 80
    targetPort: 9296