apiVersion: apps/v1
kind: Deployment
metadata:
  name: ConfigServer-app
  namespace: microsvc-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ConfigServer-app-app
  template:
    metadata:
      labels:
        app: ConfigServer-app-app
    spec:
      containers:
        - name: ConfigServer-app-app
          image: algabrizaid/configserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9296
          env:

            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka
                  key: hostname
          resources:   
            limits:
              cpu: 500m   
              memory: 512Mi  
            requests:
              cpu: 200m   
              memory: 256Mi   

---

apiVersion: v1
kind: Service
metadata:
  name: ConfigServer-app-app-svc
  namespace: microsvc-pro
spec:
  selector:
    app: service-registry-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9296
  type: NodePort 


