apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  namespace: microsvc-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
        - name: config-server-app
          image: algabrizaid/serviceregistry:latest-10
          imagePullPolicy: Always
          ports:
            - containerPort: 9296
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka
                  key: hostname
          resources:   
            limits:
              cpu: 500m   
              memory: 512Mi  
            requests:
              cpu: 200m   
              memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: config-server-app-svc
  namespace: microsvc-pro
spec:
  selector:
    app: config-server-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9296
  type: NodePort


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudgateway
  namespace: microsvc-pro
data:
  hostname: "config-server-app-svc"
