apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       —name: nginx
          image: nginx
          ports:
           —containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5














# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: spring-boot-app
#   namespace: mciroservice-project
#   labels:
#     app: spring-boot-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: spring-boot-app
#   template:
#     metadata:
#       labels:
#         app: spring-boot-app
#     spec:
#       containers:
#       - name: spring-boot-app
#         image: algabrizaid/mysql-springboot-azure:latest-15
#         ports:
#         - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: spring-boot-app-service
#   namespace: mciroservice-project
# spec:
#   type: LoadBalancer 
#   ports:
#   - name: http
#     port: 80
#     targetPort: 8080
#     protocol: TCP
#   selector:
#     app: spring-boot-app


