apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: microservice-project
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: algabrizaid/mysql-springboot-azure:latest-20
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:  
          limits:
            cpu: 500m  
            memory: 512Mi  
          requests:
            cpu: 200m   
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: microservice-project
spec:
  type: LoadBalancer 
  selector:
    app: spring-boot-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
