# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
#   namespace: microsvc-pro
#   labels:
#     app: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#       - name: mysql
#         image: mysql:8.0
#         env:
#           - name: MYSQL_ROOT_PASSWORD
#             value: zaid@11
#           # - name: MYSQL_DATABASE
#           #   value: gitops

# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-initdb-cm
# data:
#   init.sql: |
#     CREATE DATABASE IF NOT EXISTS gitops;  
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: microsvc-pro
# spec:
#   selector:
#     app: mysql
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-cm
#   namespace: microsvc-pro
# data:
#   hostname: mysql
