# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: notifications-service-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: notifications-service-app
#   template:
#     metadata:
#       labels:
#         app: notifications-service-app
#     spec:
#       containers:
#       - name: notifications-service-app
#         image: algabrizaid/notificationsservice:latest-1
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8088
#         env:
#           - name: CONFIG_SERVER_URL
#             valueFrom:
#               configMapKeyRef:
#                 name: config-cm
#                 key: config_url
#           - name: EUREKA_SERVER_ADDRESS
#             valueFrom:
#               configMapKeyRef:
#                 name: eureka-cm
#                 key: eureka_service_address
#           - name: DB_HOST
#             valueFrom:
#               configMapKeyRef:
#                 name: mysql-cm
#                 key: hostname
#   # strategy:
#   #   type: RollingUpdate
#   #   rollingUpdate:
#   #     maxUnavailable: 0
#   #     maxSurge: 1

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: notifications-service-svc
# spec:
#   selector:
#     app: notifications-service-app
#   ports:
#   - port: 80
#     targetPort: 8088
