# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv
# spec:
#   capacity:
#     storage: 256Mi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: manual
#   hostPath:
#     path: "/var/lib/mysql"
