# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc
# spec:
#   resources:
#     requests:
#       storage: 256Mi
#   storageClassName: managed 
#   accessModes:
#     - ReadWriteOnce
