apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactJs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactJs-app
  template:
    metadata:
      labels:
        app: reactJs-app
    spec:
      containers:
      - name: reactJs-app
        image: algabrizaid/reactapp:null
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
   



---

apiVersion: v1
kind: Service
metadata:
  name: reactJs-svc
spec:
  type: LoadBalancer
  selector:
    app: reactJs-app
  ports:
  - port: 80
    targetPort: 5000
