apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-service-app
  template:
    metadata:
      labels:
        app: transfer-service-app
    spec:
      containers:
      - name: transfer-service-app
        image: algabrizaid/transferservice:latest-6
        # imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-cm
                key: config_url
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-cm
                key: hostname


---

apiVersion: v1
kind: Service
metadata:
  name: transfer-service-svc
spec:
  selector:
    app: transfer-service-app
  ports:
  - port: 80
    targetPort: 8082

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pdf" 